highlighter: rouge
#permalink: /:year/:month/:day/:title/
#environment: prod
url: ""  # Sitemap base URL.
plugins:
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-feed

title: The Good Minima
description: >- # this means to ignore newlines
  A blog about implicit biases in deep learning
show_excerpts: true
# Build settings
theme: minima
